//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1DD20A
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I1DD20A()
        {
            this.PEDEPE = new HashSet<PEDEPE>();
        }
    
        public string ARTX0 { get; set; }
        public decimal ARTCIA { get; set; }
        public string ARTCITEM { get; set; }
        public string ARTDES { get; set; }
        public string ARTMED { get; set; }
        public string ARTGRINV { get; set; }
        public string ARTGIRO { get; set; }
        public string ARTGRCOM { get; set; }
        public string ARTCCOMP { get; set; }
        public decimal ARTCCONS { get; set; }
        public decimal ARTCANA1 { get; set; }
        public decimal ARTCANA2 { get; set; }
        public string ARTCLINV { get; set; }
        public string ARTCIMP1 { get; set; }
        public string ARTCIMP2 { get; set; }
        public string ARTCIMP3 { get; set; }
        public string ARTCPLTR { get; set; }
        public string ARTUPLTR { get; set; }
        public decimal ARTSTSEG { get; set; }
        public decimal ARTPREOR { get; set; }
        public decimal ARTTLOTE { get; set; }
        public decimal ARTSTMAX { get; set; }
        public decimal ARTLDREV { get; set; }
        public decimal ARTFUREV { get; set; }
        public decimal ARTTREXT { get; set; }
        public string ARTTHIST { get; set; }
        public string ARTTPROM { get; set; }
        public decimal ARTPMVL1 { get; set; }
        public decimal ARTPMVL2 { get; set; }
        public decimal ARTLDCNT { get; set; }
        public decimal ARTFUCNT { get; set; }
        public decimal ARTSTOCK { get; set; }
        public decimal ARTSTANT { get; set; }
        public decimal ARTCANOR { get; set; }
        public decimal ARTCANRE { get; set; }
        public decimal ARTPSALM { get; set; }
        public decimal ARTAASAN { get; set; }
        public decimal ARTSTVA1 { get; set; }
        public decimal ARTCOSU1 { get; set; }
        public decimal ARTCOSU2 { get; set; }
        public string ARTTCOSR { get; set; }
        public decimal ARTCOUM1 { get; set; }
        public decimal ARTCOUM2 { get; set; }
        public string ARTTMAT { get; set; }
        public decimal ARTPREU1 { get; set; }
        public decimal ARTPREU2 { get; set; }
        public string ARTCDSRC { get; set; }
        public decimal ARTSTVA2 { get; set; }
        public string ARTX1 { get; set; }
        public decimal ARTFUSAL { get; set; }
        public decimal ARTFUENT { get; set; }
        public decimal ARTFUREQ { get; set; }
        public decimal ARTFUOC { get; set; }
        public decimal ARTFALTA { get; set; }
        public decimal ARTFBAJA { get; set; }
        public decimal ARTUPTRN { get; set; }
        public string ARTCACT { get; set; }
        public decimal ARTAASAE { get; set; }
        public decimal ARTUPROV { get; set; }
        public string ARTCMON { get; set; }
        public string ARTMEDA { get; set; }
        public decimal ARTEQMED { get; set; }
        public string ARTUBI { get; set; }
        public decimal ARTSTOCM { get; set; }
        public decimal ARTCANOM { get; set; }
        public decimal ARTCANRM { get; set; }
        public string ARTACTEM { get; set; }
        public string ARTACTOM { get; set; }
        public string ARTACTRM { get; set; }
        public decimal ARTCRSG { get; set; }
        public decimal ARTNRELM { get; set; }
        public decimal ARTNRELD { get; set; }
        public decimal ARTNRELH { get; set; }
        public string ARTFCTL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDEPE> PEDEPE { get; set; }
    }
}
