//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEBODP
    {
        public decimal BODPIDDE { get; set; }
        public Nullable<decimal> BODPIDBO { get; set; }
        public Nullable<decimal> BODPIDDP { get; set; }
        public decimal BODPALMA { get; set; }
        public string BODPPART { get; set; }
        public string BODPCOAR { get; set; }
        public decimal BODPCANT { get; set; }
        public decimal BODPPESO { get; set; }
        public decimal BODPPERE { get; set; }
        public decimal BODPDIFE { get; set; }
        public Nullable<decimal> BODPIDDO { get; set; }
        public decimal BODPSTCE { get; set; }
        public decimal BODPINBO { get; set; }
        public decimal BODPTADE { get; set; }
        public decimal BODPPEBR { get; set; }
        public string BODPUSCR { get; set; }
        public System.DateTime BODPFECR { get; set; }
        public string BODPUSMO { get; set; }
        public Nullable<System.DateTime> BODPFEMO { get; set; }
        public decimal BODPESTA { get; set; }
        public decimal BODPSECR { get; set; }
        public decimal BODPTAUN { get; set; }
        public string BODPAPOR { get; set; }
    
        public virtual PEDEOS PEDEOS { get; set; }
        public virtual PEDEPE PEDEPE { get; set; }
        public virtual PEBOLS PEBOLS { get; set; }
    }
}
