//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PECASI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PECASI()
        {
            this.PEHIBO = new HashSet<PEHIBO>();
            this.PEBOLS = new HashSet<PEBOLS>();
        }
    
        public string CASICOCA { get; set; }
        public decimal CASIIDPA { get; set; }
        public string CASIIDNI { get; set; }
        public decimal CASIIDCO { get; set; }
        public Nullable<decimal> CASICAPA { get; set; }
        public decimal CASIESTA { get; set; }
        public Nullable<decimal> CASIALTU { get; set; }
        public Nullable<decimal> CASILARG { get; set; }
        public Nullable<decimal> CASIANCH { get; set; }
        public string CASIUSCR { get; set; }
        public System.DateTime CASIFECR { get; set; }
        public string CASIUSMO { get; set; }
        public Nullable<System.DateTime> CASIFEMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEHIBO> PEHIBO { get; set; }
        public virtual PECOLU PECOLU { get; set; }
        public virtual PENIVE PENIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEBOLS> PEBOLS { get; set; }
    }
}
