//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PECAPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PECAPE()
        {
            this.PEPEPG = new HashSet<PEPEPG>();
            this.PEDEPE = new HashSet<PEDEPE>();
        }
    
        public decimal CAPEIDCP { get; set; }
        public string CAPESERI { get; set; }
        public decimal CAPENUME { get; set; }
        public string CAPEIDCL { get; set; }
        public System.DateTime CAPEFECH { get; set; }
        public decimal CAPEIDES { get; set; }
        public decimal CAPEPRIO { get; set; }
        public Nullable<System.DateTime> CAPEFEPR { get; set; }
        public string CAPEUSPR { get; set; }
        public string CAPENOTI { get; set; }
        public string CAPENOTG { get; set; }
        public string CAPEUSCR { get; set; }
        public System.DateTime CAPEFECR { get; set; }
        public string CAPEUSMO { get; set; }
        public Nullable<System.DateTime> CAPEFEMO { get; set; }
        public string CAPEDIRE { get; set; }
        public string CAPEUSEM { get; set; }
        public Nullable<System.DateTime> CAPEFHEM { get; set; }
        public string CAPEUSFP { get; set; }
        public Nullable<System.DateTime> CAPEFHFP { get; set; }
        public string CAPEUSIP { get; set; }
        public Nullable<System.DateTime> CAPEFHIP { get; set; }
        public decimal CAPEEPRI { get; set; }
        public string CAPEEMAI { get; set; }
        public decimal CAPENUBU { get; set; }
        public string CAPEUSAP { get; set; }
        public Nullable<System.DateTime> CAPEFEAP { get; set; }
        public decimal CAPETIPO { get; set; }
        public Nullable<decimal> CAPEDOCO { get; set; }
        public decimal CAPETADE { get; set; }
        public decimal CAPEIDTD { get; set; }
        public string CAPEDEST { get; set; }
    
        public virtual PEESTA PEESTA { get; set; }
        public virtual TCLIE TCLIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEPEPG> PEPEPG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDEPE> PEDEPE { get; set; }
    }
}
