//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PEDIDOSEntities : DbContext
    {
        public PEDIDOSEntities()
            : base("name=PEDIDOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMCLI> AMCLI { get; set; }
        public virtual DbSet<PEDPDG> PEDPDG { get; set; }
        public virtual DbSet<PEESTA> PEESTA { get; set; }
        public virtual DbSet<PEHIBO> PEHIBO { get; set; }
        public virtual DbSet<PEHIMO> PEHIMO { get; set; }
        public virtual DbSet<PEPEPG> PEPEPG { get; set; }
        public virtual DbSet<PETIFO> PETIFO { get; set; }
        public virtual DbSet<PETMKB> PETMKB { get; set; }
        public virtual DbSet<PEUSTF> PEUSTF { get; set; }
        public virtual DbSet<PROSAS> PROSAS { get; set; }
        public virtual DbSet<TCLIE> TCLIE { get; set; }
        public virtual DbSet<PECAPE> PECAPE { get; set; }
        public virtual DbSet<I1DD20A> I1DD20A { get; set; }
        public virtual DbSet<VSED00A> VSED00A { get; set; }
        public virtual DbSet<VSED02A> VSED02A { get; set; }
        public virtual DbSet<FCTIEM> FCTIEM { get; set; }
        public virtual DbSet<GMCAEM> GMCAEM { get; set; }
        public virtual DbSet<PECASI> PECASI { get; set; }
        public virtual DbSet<PECOLU> PECOLU { get; set; }
        public virtual DbSet<PENIVE> PENIVE { get; set; }
        public virtual DbSet<PEPASI> PEPASI { get; set; }
        public virtual DbSet<PETICO> PETICO { get; set; }
        public virtual DbSet<PECAOS> PECAOS { get; set; }
        public virtual DbSet<PEDEPE> PEDEPE { get; set; }
        public virtual DbSet<PEKABO> PEKABO { get; set; }
        public virtual DbSet<PEDEOS> PEDEOS { get; set; }
        public virtual DbSet<PEBODP> PEBODP { get; set; }
        public virtual DbSet<GMDEEM> GMDEEM { get; set; }
        public virtual DbSet<PEPARM> PEPARM { get; set; }
        public virtual DbSet<PEBOLS> PEBOLS { get; set; }
    
        public virtual ObjectResult<USP_OBTIENE_UBICACIONES_Result> USP_OBTIENE_UBICACIONES(string pARTI, string pPART, Nullable<decimal> pALMA)
        {
            var pARTIParameter = pARTI != null ?
                new ObjectParameter("PARTI", pARTI) :
                new ObjectParameter("PARTI", typeof(string));
    
            var pPARTParameter = pPART != null ?
                new ObjectParameter("PPART", pPART) :
                new ObjectParameter("PPART", typeof(string));
    
            var pALMAParameter = pALMA.HasValue ?
                new ObjectParameter("PALMA", pALMA) :
                new ObjectParameter("PALMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_UBICACIONES_Result>("USP_OBTIENE_UBICACIONES", pARTIParameter, pPARTParameter, pALMAParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_BOLSA_UBICACION_Result> USP_OBTIENE_BOLSA_UBICACION(string pCOEM)
        {
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_BOLSA_UBICACION_Result>("USP_OBTIENE_BOLSA_UBICACION", pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETALLE_BOLSA_Result> USP_OBTIENE_DETALLE_BOLSA(string pCOEM)
        {
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETALLE_BOLSA_Result>("USP_OBTIENE_DETALLE_BOLSA", pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_PEDIDO_CONSULTA_Result> USP_OBTIENE_PEDIDO_CONSULTA(Nullable<decimal> iD_PED)
        {
            var iD_PEDParameter = iD_PED.HasValue ?
                new ObjectParameter("ID_PED", iD_PED) :
                new ObjectParameter("ID_PED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_PEDIDO_CONSULTA_Result>("USP_OBTIENE_PEDIDO_CONSULTA", iD_PEDParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETALLE_OSA_PLANTA_Result> USP_OBTIENE_DETALLE_OSA_PLANTA(string pFOLIO)
        {
            var pFOLIOParameter = pFOLIO != null ?
                new ObjectParameter("PFOLIO", pFOLIO) :
                new ObjectParameter("PFOLIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETALLE_OSA_PLANTA_Result>("USP_OBTIENE_DETALLE_OSA_PLANTA", pFOLIOParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETALLE_PEDIDOS_Result> USP_OBTIENE_DETALLE_PEDIDOS(Nullable<decimal> iD_PED)
        {
            var iD_PEDParameter = iD_PED.HasValue ?
                new ObjectParameter("ID_PED", iD_PED) :
                new ObjectParameter("ID_PED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETALLE_PEDIDOS_Result>("USP_OBTIENE_DETALLE_PEDIDOS", iD_PEDParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_OSAS_PENDIENTES_Result> USP_OBTIENE_OSAS_PENDIENTES(string pTIPFOL, string pPARTID)
        {
            var pTIPFOLParameter = pTIPFOL != null ?
                new ObjectParameter("PTIPFOL", pTIPFOL) :
                new ObjectParameter("PTIPFOL", typeof(string));
    
            var pPARTIDParameter = pPARTID != null ?
                new ObjectParameter("PPARTID", pPARTID) :
                new ObjectParameter("PPARTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_OSAS_PENDIENTES_Result>("USP_OBTIENE_OSAS_PENDIENTES", pTIPFOLParameter, pPARTIDParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETALLE_OSA_Result> USP_OBTIENE_DETALLE_OSA(string pFOLIO)
        {
            var pFOLIOParameter = pFOLIO != null ?
                new ObjectParameter("PFOLIO", pFOLIO) :
                new ObjectParameter("PFOLIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETALLE_OSA_Result>("USP_OBTIENE_DETALLE_OSA", pFOLIOParameter);
        }
    
        public virtual ObjectResult<USP_FOLIO_USUARIO_Result> USP_FOLIO_USUARIO(string uSUARIO)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_FOLIO_USUARIO_Result>("USP_FOLIO_USUARIO", uSUARIOParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_BOLSA_OSA_Result> USP_OBTIENE_BOLSA_OSA(Nullable<decimal> pIDDO, string pCOEM)
        {
            var pIDDOParameter = pIDDO.HasValue ?
                new ObjectParameter("PIDDO", pIDDO) :
                new ObjectParameter("PIDDO", typeof(decimal));
    
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_BOLSA_OSA_Result>("USP_OBTIENE_BOLSA_OSA", pIDDOParameter, pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_BOLSA_Result> USP_OBTIENE_BOLSA(Nullable<decimal> pIDDP, string pCOEM)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_BOLSA_Result>("USP_OBTIENE_BOLSA", pIDDPParameter, pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETOSA_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETOSA(Nullable<decimal> pIDDO)
        {
            var pIDDOParameter = pIDDO.HasValue ?
                new ObjectParameter("PIDDO", pIDDO) :
                new ObjectParameter("PIDDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETOSA_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETOSA", pIDDOParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETALLE_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETALLE(Nullable<decimal> pIDDP)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETALLE_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETALLE", pIDDPParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_OSAS_PENDIENTES_PLANTA_Result> USP_OBTIENE_OSAS_PENDIENTES_PLANTA(string pTIPFOL, string vALBUS)
        {
            var pTIPFOLParameter = pTIPFOL != null ?
                new ObjectParameter("PTIPFOL", pTIPFOL) :
                new ObjectParameter("PTIPFOL", typeof(string));
    
            var vALBUSParameter = vALBUS != null ?
                new ObjectParameter("VALBUS", vALBUS) :
                new ObjectParameter("VALBUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_OSAS_PENDIENTES_PLANTA_Result>("USP_OBTIENE_OSAS_PENDIENTES_PLANTA", pTIPFOLParameter, vALBUSParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTA_EMPAQUES_PARTIDA_Result> USP_CONSULTA_EMPAQUES_PARTIDA(string pPART, string pITEM, string pCOEM)
        {
            var pPARTParameter = pPART != null ?
                new ObjectParameter("PPART", pPART) :
                new ObjectParameter("PPART", typeof(string));
    
            var pITEMParameter = pITEM != null ?
                new ObjectParameter("PITEM", pITEM) :
                new ObjectParameter("PITEM", typeof(string));
    
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTA_EMPAQUES_PARTIDA_Result>("USP_CONSULTA_EMPAQUES_PARTIDA", pPARTParameter, pITEMParameter, pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE(Nullable<decimal> pIDDP)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE", pIDDPParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETOSASE_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETOSASE(Nullable<decimal> pIDDO)
        {
            var pIDDOParameter = pIDDO.HasValue ?
                new ObjectParameter("PIDDO", pIDDO) :
                new ObjectParameter("PIDDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETOSASE_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETOSASE", pIDDOParameter);
        }
    }
}
