//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEESTA()
        {
            this.PECAPE = new HashSet<PECAPE>();
            this.PECAOS = new HashSet<PECAOS>();
        }
    
        public decimal ESTAIDES { get; set; }
        public string ESTADESC { get; set; }
        public string ESTAUSCR { get; set; }
        public System.DateTime ESTAFECR { get; set; }
        public string ESTAUSMO { get; set; }
        public Nullable<System.DateTime> ESTAFEMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PECAPE> PECAPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PECAOS> PECAOS { get; set; }
    }
}
