//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEHIBO
    {
        public decimal HIBOIDHU { get; set; }
        public string HIBOCOCA { get; set; }
        public decimal HIBOIDBO { get; set; }
        public System.DateTime HIBOFECH { get; set; }
        public string HIBOUSCR { get; set; }
        public System.DateTime HIBOFECR { get; set; }
        public string HIBOUSMO { get; set; }
        public Nullable<System.DateTime> HIBOFEMO { get; set; }
    
        public virtual PECASI PECASI { get; set; }
        public virtual PEBOLS PEBOLS { get; set; }
    }
}
