//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETMKB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PETMKB()
        {
            this.PEKABO = new HashSet<PEKABO>();
        }
    
        public decimal TMKBIDTM { get; set; }
        public string TMKBDESC { get; set; }
        public string TMKBUSCR { get; set; }
        public System.DateTime TMKBFECR { get; set; }
        public string TMKBUSMO { get; set; }
        public Nullable<System.DateTime> TMKBFEMO { get; set; }
        public string TMKBSIGN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEKABO> PEKABO { get; set; }
    }
}
