//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCLI
    {
        public decimal MCCIA { get; set; }
        public decimal MCCOCL { get; set; }
        public string MCNOCL { get; set; }
        public string MCSICL { get; set; }
        public string MCRUC { get; set; }
        public string MCCNVT { get; set; }
        public string MCCOAG { get; set; }
        public string MCFIL { get; set; }
        public string MCSTAT { get; set; }
    }
}
