//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSALES
    {
        public decimal ALESCIA { get; set; }
        public string ALESESTA { get; set; }
        public decimal ALESALMA { get; set; }
        public string ALESDESC { get; set; }
        public string ALESPROP { get; set; }
        public string ALESSTAT { get; set; }
        public string ALESFLG1 { get; set; }
        public string ALESFLG2 { get; set; }
        public string ALESFLG3 { get; set; }
    }
}
