//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCTIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCTIEM()
        {
            this.GMCAEM = new HashSet<GMCAEM>();
        }
    
        public decimal TIEMCIA { get; set; }
        public string TIEMCOTE { get; set; }
        public string TIEMDETE { get; set; }
        public string TIEMTIPO { get; set; }
        public decimal TIEMLARG { get; set; }
        public decimal TIEMANCH { get; set; }
        public decimal TIEMALTU { get; set; }
        public decimal TIEMTIES { get; set; }
        public decimal TIEMTARA { get; set; }
        public decimal TIEMACON { get; set; }
        public string TIEMARTI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GMCAEM> GMCAEM { get; set; }
    }
}
