//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMCAEM
    {
        public decimal CAEMCIA { get; set; }
        public string CAEMCOEM { get; set; }
        public System.DateTime CAEMFECH { get; set; }
        public decimal CAEMTURN { get; set; }
        public decimal CAEMPNTO { get; set; }
        public decimal CAEMDTTO { get; set; }
        public decimal CAEMDEEM { get; set; }
        public decimal CAEMACTO { get; set; }
        public decimal CAEMPBTO { get; set; }
        public decimal CAEMCAIT { get; set; }
        public string CAEMTIEM { get; set; }
        public string CAEMNPED { get; set; }
        public string CAEMDESP { get; set; }
        public string CAEMNNDC { get; set; }
        public decimal CAEMALMA { get; set; }
        public string CAEMPART { get; set; }
        public string CAEMMSPA { get; set; }
        public string CAEMESEM { get; set; }
        public string CAEMESRE { get; set; }
        public string CAEMUSER { get; set; }
        public string CAEMRESP { get; set; }
        public string CAEMUBIC { get; set; }
    
        public virtual FCTIEM FCTIEM { get; set; }
    }
}
