//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMDEEM
    {
        public decimal DEEMCIA { get; set; }
        public string DEEMCOEM { get; set; }
        public decimal DEEMSECU { get; set; }
        public System.DateTime DEEMFECH { get; set; }
        public System.DateTime DEEMHORA { get; set; }
        public string DEEMPART { get; set; }
        public string DEEMARTI { get; set; }
        public decimal DEEMALMA { get; set; }
        public decimal DEEMCANT { get; set; }
        public string DEEMTIPE { get; set; }
        public decimal DEEMPNET { get; set; }
        public decimal DEEMDEST { get; set; }
        public decimal DEEMACON { get; set; }
        public string DEEMUSER { get; set; }
        public string DEEMESTA { get; set; }
        public decimal DEEMCAST { get; set; }
        public decimal DEEMPEST { get; set; }
        public decimal DEEMSTCE { get; set; }
        public decimal DEEMESBO { get; set; }
    }
}
