//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class I1DD41A
    {
        public decimal LOTCIA { get; set; }
        public string LOTITEM { get; set; }
        public string LOTPARTI { get; set; }
        public decimal LOTALM { get; set; }
        public decimal LOTSTOCK { get; set; }
        public decimal LOTCANOR { get; set; }
        public decimal LOTCANRE { get; set; }
        public decimal LOTFDOCU { get; set; }
        public decimal LOTSALPA { get; set; }
        public string LOTX0 { get; set; }
        public string LOTSTPAR { get; set; }
        public string LOTUBIFI { get; set; }
        public decimal LOTCAUNI { get; set; }
    }
}
