//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PEDIDOSEntities : DbContext
    {
        public PEDIDOSEntities()
            : base("name=PEDIDOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMCLI> AMCLI { get; set; }
        public virtual DbSet<PECAOS> PECAOS { get; set; }
        public virtual DbSet<PEDPDG> PEDPDG { get; set; }
        public virtual DbSet<PEESTA> PEESTA { get; set; }
        public virtual DbSet<PEHIBO> PEHIBO { get; set; }
        public virtual DbSet<PEHIMO> PEHIMO { get; set; }
        public virtual DbSet<PEPEPG> PEPEPG { get; set; }
        public virtual DbSet<PETIFO> PETIFO { get; set; }
        public virtual DbSet<PETMKB> PETMKB { get; set; }
        public virtual DbSet<PEUSTF> PEUSTF { get; set; }
        public virtual DbSet<PROSAS> PROSAS { get; set; }
        public virtual DbSet<TCLIE> TCLIE { get; set; }
        public virtual DbSet<I1DD20A> I1DD20A { get; set; }
        public virtual DbSet<VSED00A> VSED00A { get; set; }
        public virtual DbSet<VSED02A> VSED02A { get; set; }
        public virtual DbSet<FCTIEM> FCTIEM { get; set; }
        public virtual DbSet<GMCAEM> GMCAEM { get; set; }
        public virtual DbSet<GMDEEM> GMDEEM { get; set; }
        public virtual DbSet<PECASI> PECASI { get; set; }
        public virtual DbSet<PECOLU> PECOLU { get; set; }
        public virtual DbSet<PENIVE> PENIVE { get; set; }
        public virtual DbSet<PEPASI> PEPASI { get; set; }
        public virtual DbSet<PETICO> PETICO { get; set; }
        public virtual DbSet<PEKABO> PEKABO { get; set; }
        public virtual DbSet<I1DD41A> I1DD41A { get; set; }
        public virtual DbSet<PEDEOS> PEDEOS { get; set; }
        public virtual DbSet<PRCALI> PRCALI { get; set; }
        public virtual DbSet<PRPART> PRPART { get; set; }
        public virtual DbSet<CSALES> CSALES { get; set; }
        public virtual DbSet<PEDEPE> PEDEPE { get; set; }
        public virtual DbSet<PEPARM> PEPARM { get; set; }
        public virtual DbSet<PRASIG> PRASIG { get; set; }
        public virtual DbSet<PEBOLS> PEBOLS { get; set; }
        public virtual DbSet<PECAPE> PECAPE { get; set; }
        public virtual DbSet<PEBODP> PEBODP { get; set; }
    
        public virtual ObjectResult<USP_OBTIENE_UBICACIONES_Result> USP_OBTIENE_UBICACIONES(string pARTI, string pPART, Nullable<decimal> pALMA)
        {
            var pARTIParameter = pARTI != null ?
                new ObjectParameter("PARTI", pARTI) :
                new ObjectParameter("PARTI", typeof(string));
    
            var pPARTParameter = pPART != null ?
                new ObjectParameter("PPART", pPART) :
                new ObjectParameter("PPART", typeof(string));
    
            var pALMAParameter = pALMA.HasValue ?
                new ObjectParameter("PALMA", pALMA) :
                new ObjectParameter("PALMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_UBICACIONES_Result>("USP_OBTIENE_UBICACIONES", pARTIParameter, pPARTParameter, pALMAParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_PEDIDO_ALMACEN_Result> USP_OBTIENE_PEDIDO_ALMACEN(Nullable<int> iD_ESTADO)
        {
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_PEDIDO_ALMACEN_Result>("USP_OBTIENE_PEDIDO_ALMACEN", iD_ESTADOParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_PEDIDO_FECHAS_Result> USP_OBTIENE_PEDIDO_FECHAS(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, Nullable<int> iD_ESTADO)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_PEDIDO_FECHAS_Result>("USP_OBTIENE_PEDIDO_FECHAS", fECHA_INICIOParameter, fECHA_FINParameter, iD_ESTADOParameter);
        }
    
        public virtual ObjectResult<USP_REPORTE_EMPAQUES_PARTIDA_Result> USP_REPORTE_EMPAQUES_PARTIDA(string pPART, Nullable<decimal> pALMA)
        {
            var pPARTParameter = pPART != null ?
                new ObjectParameter("PPART", pPART) :
                new ObjectParameter("PPART", typeof(string));
    
            var pALMAParameter = pALMA.HasValue ?
                new ObjectParameter("PALMA", pALMA) :
                new ObjectParameter("PALMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_REPORTE_EMPAQUES_PARTIDA_Result>("USP_REPORTE_EMPAQUES_PARTIDA", pPARTParameter, pALMAParameter);
        }
    
        public virtual ObjectResult<USP_REPORTE_MOVIMIENTOS_PARTIDA_Result> USP_REPORTE_MOVIMIENTOS_PARTIDA(string pPART, Nullable<decimal> pALMA)
        {
            var pPARTParameter = pPART != null ?
                new ObjectParameter("PPART", pPART) :
                new ObjectParameter("PPART", typeof(string));
    
            var pALMAParameter = pALMA.HasValue ?
                new ObjectParameter("PALMA", pALMA) :
                new ObjectParameter("PALMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_REPORTE_MOVIMIENTOS_PARTIDA_Result>("USP_REPORTE_MOVIMIENTOS_PARTIDA", pPARTParameter, pALMAParameter);
        }
    
        public virtual ObjectResult<USP_REPORTE_MOVIMIENTOS_FECHAS_Result> USP_REPORTE_MOVIMIENTOS_FECHAS(Nullable<System.DateTime> pFECHINI, Nullable<System.DateTime> pFECHFIN)
        {
            var pFECHINIParameter = pFECHINI.HasValue ?
                new ObjectParameter("PFECHINI", pFECHINI) :
                new ObjectParameter("PFECHINI", typeof(System.DateTime));
    
            var pFECHFINParameter = pFECHFIN.HasValue ?
                new ObjectParameter("PFECHFIN", pFECHFIN) :
                new ObjectParameter("PFECHFIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_REPORTE_MOVIMIENTOS_FECHAS_Result>("USP_REPORTE_MOVIMIENTOS_FECHAS", pFECHINIParameter, pFECHFINParameter);
        }
    
        public virtual ObjectResult<USP_BUSCA_CLIENTE_Result> USP_BUSCA_CLIENTE(string pVALBUS)
        {
            var pVALBUSParameter = pVALBUS != null ?
                new ObjectParameter("PVALBUS", pVALBUS) :
                new ObjectParameter("PVALBUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BUSCA_CLIENTE_Result>("USP_BUSCA_CLIENTE", pVALBUSParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_BOLSA_Result> USP_OBTIENE_BOLSA(Nullable<decimal> pIDDP, string pCOEM)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            var pCOEMParameter = pCOEM != null ?
                new ObjectParameter("PCOEM", pCOEM) :
                new ObjectParameter("PCOEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_BOLSA_Result>("USP_OBTIENE_BOLSA", pIDDPParameter, pCOEMParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETALLE_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETALLE(Nullable<decimal> pIDDP)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETALLE_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETALLE", pIDDPParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_ARTICULOS_Result> USP_OBTIENE_ARTICULOS(string pNUPE, string pNUPA, string pITEM, string pPRST)
        {
            var pNUPEParameter = pNUPE != null ?
                new ObjectParameter("PNUPE", pNUPE) :
                new ObjectParameter("PNUPE", typeof(string));
    
            var pNUPAParameter = pNUPA != null ?
                new ObjectParameter("PNUPA", pNUPA) :
                new ObjectParameter("PNUPA", typeof(string));
    
            var pITEMParameter = pITEM != null ?
                new ObjectParameter("PITEM", pITEM) :
                new ObjectParameter("PITEM", typeof(string));
    
            var pPRSTParameter = pPRST != null ?
                new ObjectParameter("PPRST", pPRST) :
                new ObjectParameter("PPRST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_ARTICULOS_Result>("USP_OBTIENE_ARTICULOS", pNUPEParameter, pNUPAParameter, pITEMParameter, pPRSTParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETALLE_PEDIDOS_Result> USP_OBTIENE_DETALLE_PEDIDOS(Nullable<decimal> iD_PED)
        {
            var iD_PEDParameter = iD_PED.HasValue ?
                new ObjectParameter("ID_PED", iD_PED) :
                new ObjectParameter("ID_PED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETALLE_PEDIDOS_Result>("USP_OBTIENE_DETALLE_PEDIDOS", iD_PEDParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_PEDIDO_CONSULTA_Result> USP_OBTIENE_PEDIDO_CONSULTA(Nullable<decimal> iD_PED)
        {
            var iD_PEDParameter = iD_PED.HasValue ?
                new ObjectParameter("ID_PED", iD_PED) :
                new ObjectParameter("ID_PED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_PEDIDO_CONSULTA_Result>("USP_OBTIENE_PEDIDO_CONSULTA", iD_PEDParameter);
        }
    
        public virtual ObjectResult<USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE_Result> USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE(Nullable<decimal> pIDDP)
        {
            var pIDDPParameter = pIDDP.HasValue ?
                new ObjectParameter("PIDDP", pIDDP) :
                new ObjectParameter("PIDDP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE_Result>("USP_OBTIENE_DETPREPARACION_POR_IDDETALLESE", pIDDPParameter);
        }
    }
}
