//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEHIMO
    {
        public decimal HIMOIDIM { get; set; }
        public string HIMOCOAR { get; set; }
        public Nullable<decimal> HIMOIDDO { get; set; }
        public Nullable<decimal> HIMOIDDP { get; set; }
        public decimal HIMOIDBO { get; set; }
        public System.DateTime HIMOFECH { get; set; }
        public Nullable<decimal> HIMOCANT { get; set; }
        public decimal HIMOPESO { get; set; }
        public string HIMOUSCR { get; set; }
        public System.DateTime HIMOFECR { get; set; }
        public string HIMOUSMO { get; set; }
        public Nullable<System.DateTime> HIMOFEMO { get; set; }
    
        public virtual PEDEOS PEDEOS { get; set; }
        public virtual PEDEPE PEDEPE { get; set; }
        public virtual PEBOLS PEBOLS { get; set; }
    }
}
