//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEKABO
    {
        public decimal KABOIDKB { get; set; }
        public decimal KABOIDBO { get; set; }
        public decimal KABOIDTM { get; set; }
        public System.DateTime KABOFECH { get; set; }
        public decimal KABOCANT { get; set; }
        public decimal KABOPESO { get; set; }
        public Nullable<decimal> KABOIDDP { get; set; }
        public Nullable<decimal> KABOIDDO { get; set; }
        public string KABOUSCR { get; set; }
        public System.DateTime KABOFECR { get; set; }
        public string KABOUSMO { get; set; }
        public Nullable<System.DateTime> KABOFEMO { get; set; }
        public string KABOPART { get; set; }
        public string KABOITEM { get; set; }
        public decimal KABOTARA { get; set; }
        public decimal KABOPEBR { get; set; }
        public decimal KABOALMA { get; set; }
    
        public virtual PETMKB PETMKB { get; set; }
        public virtual PEBOLS PEBOLS { get; set; }
    }
}
