//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PENIVE()
        {
            this.PECASI = new HashSet<PECASI>();
        }
    
        public string NIVEIDNI { get; set; }
        public decimal NIVEIDPA { get; set; }
        public decimal NIVEESTA { get; set; }
        public string NIVEUSCR { get; set; }
        public System.DateTime NIVEFECR { get; set; }
        public string NIVEUSMO { get; set; }
        public Nullable<System.DateTime> NIVEFEMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PECASI> PECASI { get; set; }
        public virtual PEPASI PEPASI { get; set; }
    }
}
