//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEPASI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEPASI()
        {
            this.PECOLU = new HashSet<PECOLU>();
            this.PENIVE = new HashSet<PENIVE>();
        }
    
        public decimal PASIIDPA { get; set; }
        public decimal PASIESTA { get; set; }
        public string PASIUSCR { get; set; }
        public System.DateTime PASIFECR { get; set; }
        public string PASIUSMO { get; set; }
        public Nullable<System.DateTime> PASIFEMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PECOLU> PECOLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENIVE> PENIVE { get; set; }
    }
}
