//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEPEPG
    {
        public decimal PEPGIDPP { get; set; }
        public decimal PEPGIDCP { get; set; }
        public decimal PEPGIDPG { get; set; }
        public string PEPGUSCR { get; set; }
        public System.DateTime PEPGFECR { get; set; }
        public string PEPGUSMO { get; set; }
        public Nullable<System.DateTime> PEPGFEMO { get; set; }
    
        public virtual PECAPE PECAPE { get; set; }
    }
}
