//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETIFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PETIFO()
        {
            this.PEUSTF = new HashSet<PEUSTF>();
        }
    
        public decimal TIFOIDTF { get; set; }
        public string TIFOCOFO { get; set; }
        public string TIFODESC { get; set; }
        public string TIFOUSCR { get; set; }
        public System.DateTime TIFOFECR { get; set; }
        public string TIFOUSMO { get; set; }
        public Nullable<System.DateTime> TIFOFEMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEUSTF> PEUSTF { get; set; }
    }
}
