//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETICO
    {
        public decimal TICOIDTC { get; set; }
        public string TICODESC { get; set; }
        public decimal TICOPESO { get; set; }
        public decimal TICOALTU { get; set; }
        public decimal TICOLARG { get; set; }
        public decimal TICOANCH { get; set; }
        public string TICOUSCR { get; set; }
        public System.DateTime TICOFECR { get; set; }
        public string TICOUSMO { get; set; }
        public Nullable<System.DateTime> TICOFEMO { get; set; }
    }
}
