//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRASIG
    {
        public decimal ASIGCIA { get; set; }
        public string ASIGNUPA { get; set; }
        public string ASIGNUPE { get; set; }
        public string ASIGTIPE { get; set; }
        public decimal ASIGSEPE { get; set; }
        public decimal ASIGSEPI { get; set; }
        public decimal ASIGCLIE { get; set; }
        public System.DateTime ASIGFERQ { get; set; }
        public decimal ASIGCAPR { get; set; }
        public decimal ASIGCAFA { get; set; }
        public decimal ASIGALIN { get; set; }
        public string ASIGSTAT { get; set; }
        public decimal ASIGPUNS { get; set; }
    }
}
