//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRCALI
    {
        public decimal CALICIA { get; set; }
        public string CALICODI { get; set; }
        public string CALIGRUP { get; set; }
        public string CALISIGL { get; set; }
        public string CALIDEAB { get; set; }
        public string CALICOMP { get; set; }
        public string CALIABRE { get; set; }
        public string CALIFLCB { get; set; }
        public string CALIFLNT { get; set; }
        public string CALIBASE { get; set; }
        public string CALIFLLF { get; set; }
        public string CALIFICA { get; set; }
        public decimal CALIMIST { get; set; }
        public decimal CALILOST { get; set; }
        public decimal CALIREF0 { get; set; }
        public decimal CALIREW0 { get; set; }
        public decimal CALIRES0 { get; set; }
        public decimal CALIRET0 { get; set; }
        public decimal CALIREH0 { get; set; }
        public string CALISTAT { get; set; }
        public string CALIFDES { get; set; }
    }
}
