//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRPART
    {
        public decimal PARTCIA { get; set; }
        public string PARTNUPA { get; set; }
        public string PARTPLTA { get; set; }
        public string PARTARTI { get; set; }
        public decimal PARTCAPR { get; set; }
        public decimal PARTCAFA { get; set; }
        public decimal PARTCAMP { get; set; }
        public System.DateTime PARTFEEM { get; set; }
        public System.DateTime PARTFEIA { get; set; }
        public System.DateTime PARTFEEF { get; set; }
        public System.DateTime PARTFECS { get; set; }
        public System.DateTime PARTFEST { get; set; }
        public string PARTSTPR { get; set; }
        public decimal PARTREND { get; set; }
        public decimal PARTGRCA { get; set; }
        public string PARTTTR1 { get; set; }
        public decimal PARTTOR1 { get; set; }
        public string PARTTTR2 { get; set; }
        public decimal PARTTOR2 { get; set; }
        public string PARTTTR3 { get; set; }
        public decimal PARTTOR3 { get; set; }
        public string PARTVAPO { get; set; }
        public string PARTSPLC { get; set; }
        public string PARTPRFN { get; set; }
        public string PARTFANT { get; set; }
        public string PARTSERV { get; set; }
        public string PARTPROC { get; set; }
        public decimal PARTPESO { get; set; }
        public decimal PARTLONG { get; set; }
        public string PARTTPOV { get; set; }
        public string PARTEMBO { get; set; }
        public string PARTETIQ { get; set; }
        public string PARTCOLO { get; set; }
        public string PARTCOIN { get; set; }
        public string PARTSTAT { get; set; }
    }
}
