//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCLIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCLIE()
        {
            this.PECAPE = new HashSet<PECAPE>();
        }
    
        public string CLICVE { get; set; }
        public string CLINOM { get; set; }
        public string CLIABR { get; set; }
        public string CLIDIR { get; set; }
        public string CLICPO { get; set; }
        public string CLIDIS { get; set; }
        public string CLIPRO { get; set; }
        public string CLIDPT { get; set; }
        public string CLIPAI { get; set; }
        public string CLITE1 { get; set; }
        public string CLITE2 { get; set; }
        public string CLITE3 { get; set; }
        public string CLITE4 { get; set; }
        public string CLIRUC { get; set; }
        public string CLIRF1 { get; set; }
        public string CLIRF2 { get; set; }
        public string CLIRF3 { get; set; }
        public string CLIVEN { get; set; }
        public string CLICOB { get; set; }
        public string CLIZON { get; set; }
        public string CLISIT { get; set; }
        public decimal CLILCR { get; set; }
        public decimal CLISAL { get; set; }
        public string CLISCR { get; set; }
        public string CPACVE { get; set; }
        public decimal CLDSCT { get; set; }
        public string CLPREC { get; set; }
        public string CLCNOM { get; set; }
        public string CLCPUE { get; set; }
        public string CLMAIL { get; set; }
        public string CLTIDE { get; set; }
        public string CLNIDE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PECAPE> PECAPE { get; set; }
    }
}
