//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSED02A
    {
        public decimal CVTDCIA { get; set; }
        public string CVTDNUCO { get; set; }
        public string CVTDEMBA { get; set; }
        public string CVTDTCON { get; set; }
        public decimal CVTDSECU { get; set; }
        public string CVTDCOCL { get; set; }
        public string CVTDARTI { get; set; }
        public decimal CVTDPRUN { get; set; }
        public string CVTDCALV { get; set; }
        public decimal CVTDCANT { get; set; }
        public decimal CVTDIMDE { get; set; }
        public decimal CVTDSAPE { get; set; }
        public string CVTDVIA { get; set; }
        public string CVTDCDAD { get; set; }
        public string CVTDTEÑI { get; set; }
        public string CVTDMEZC { get; set; }
        public string CVTDTPFE { get; set; }
        public string CVTDSTPR { get; set; }
        public string CVTDFANT { get; set; }
        public decimal CVTDFECO { get; set; }
        public decimal CVTDFEMO { get; set; }
        public decimal CVTDFERL { get; set; }
        public string CVTDTTZ1 { get; set; }
        public decimal CVTDTOR1 { get; set; }
        public string CVTDTTZ2 { get; set; }
        public decimal CVTDTOR2 { get; set; }
        public string CVTDVAPO { get; set; }
        public decimal CVTDPESO { get; set; }
        public decimal CVTDLONG { get; set; }
        public decimal CVTDTPOE { get; set; }
        public string CVTDETIQ { get; set; }
        public string CVTDACAB { get; set; }
        public string CVTDSTAT { get; set; }
    }
}
