//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSED00A
    {
        public decimal CVTCCIA { get; set; }
        public string CVTCNUCO { get; set; }
        public string CVTCEMBA { get; set; }
        public string CVTCTCON { get; set; }
        public decimal CVTCSECU { get; set; }
        public string CVTCCDCL { get; set; }
        public decimal CVTCIFOB { get; set; }
        public decimal CVTCIFLE { get; set; }
        public decimal CVTCISEG { get; set; }
        public decimal CVTCITOT { get; set; }
        public string CVTCREFE { get; set; }
        public string CVTCMTRA { get; set; }
        public string CVTCCLFA { get; set; }
        public decimal CVTCCDIR { get; set; }
        public decimal CVTCFEMO { get; set; }
        public decimal CVTCFEMM { get; set; }
        public decimal CVTCFERL { get; set; }
        public string CVTCMPAG { get; set; }
        public string CVTCCONF { get; set; }
        public decimal CVTCFING { get; set; }
        public decimal CVTCOPFI { get; set; }
        public string CVTCEMPA { get; set; }
        public decimal CVTCFACT { get; set; }
        public decimal CVTCCTOT { get; set; }
        public string CVTC1 { get; set; }
        public string CVTCTPCO { get; set; }
        public string CVTCPECO { get; set; }
        public string CVTCPUDE { get; set; }
        public string CVTCCCOM { get; set; }
        public decimal CVTCPCOM { get; set; }
        public decimal CVTCIDIO { get; set; }
        public string CVTC2 { get; set; }
        public string CVTCLIPR { get; set; }
        public decimal CVTCIARA { get; set; }
        public string CVTCTPMO { get; set; }
        public string CVTCBANC { get; set; }
        public decimal CVTCVACC { get; set; }
        public decimal CVTCPCON { get; set; }
        public decimal CVTCTPCA { get; set; }
        public string CVTCAGVE { get; set; }
        public decimal CVTCNDET { get; set; }
        public string CVTCTPEM { get; set; }
        public string CVTCSTAT { get; set; }
    }
}
