//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appLogica.sgus003Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PAROPE", Namespace="http://schemas.datacontract.org/2004/07/SGUS003")]
    [System.SerializableAttribute()]
    public partial class PAROPE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODOPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] VALENTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODOPE {
            get {
                return this.CODOPEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODOPEField, value) != true)) {
                    this.CODOPEField = value;
                    this.RaisePropertyChanged("CODOPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] VALENT {
            get {
                return this.VALENTField;
            }
            set {
                if ((object.ReferenceEquals(this.VALENTField, value) != true)) {
                    this.VALENTField = value;
                    this.RaisePropertyChanged("VALENT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RESOPE", Namespace="http://schemas.datacontract.org/2004/07/SGUS003")]
    [System.SerializableAttribute()]
    public partial class RESOPE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ESTOPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENERRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] VALSALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ESTOPE {
            get {
                return this.ESTOPEField;
            }
            set {
                if ((this.ESTOPEField.Equals(value) != true)) {
                    this.ESTOPEField = value;
                    this.RaisePropertyChanged("ESTOPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENERR {
            get {
                return this.MENERRField;
            }
            set {
                if ((object.ReferenceEquals(this.MENERRField, value) != true)) {
                    this.MENERRField = value;
                    this.RaisePropertyChanged("MENERR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] VALSAL {
            get {
                return this.VALSALField;
            }
            set {
                if ((object.ReferenceEquals(this.VALSALField, value) != true)) {
                    this.VALSALField = value;
                    this.RaisePropertyChanged("VALSAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sgus003Service.Isgus003Service")]
    public interface Isgus003Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isgus003Service/EjecutaOperacion", ReplyAction="http://tempuri.org/Isgus003Service/EjecutaOperacionResponse")]
        appLogica.sgus003Service.RESOPE EjecutaOperacion(appLogica.sgus003Service.PAROPE paramOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isgus003Service/EjecutaOperacion", ReplyAction="http://tempuri.org/Isgus003Service/EjecutaOperacionResponse")]
        System.Threading.Tasks.Task<appLogica.sgus003Service.RESOPE> EjecutaOperacionAsync(appLogica.sgus003Service.PAROPE paramOperacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Isgus003ServiceChannel : appLogica.sgus003Service.Isgus003Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Isgus003ServiceClient : System.ServiceModel.ClientBase<appLogica.sgus003Service.Isgus003Service>, appLogica.sgus003Service.Isgus003Service {
        
        public Isgus003ServiceClient() {
        }
        
        public Isgus003ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Isgus003ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isgus003ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isgus003ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public appLogica.sgus003Service.RESOPE EjecutaOperacion(appLogica.sgus003Service.PAROPE paramOperacion) {
            return base.Channel.EjecutaOperacion(paramOperacion);
        }
        
        public System.Threading.Tasks.Task<appLogica.sgus003Service.RESOPE> EjecutaOperacionAsync(appLogica.sgus003Service.PAROPE paramOperacion) {
            return base.Channel.EjecutaOperacionAsync(paramOperacion);
        }
    }
}
